#!/usr/bin/env python3
"""Weekly review: render the brain's home page and last seven days as a review action; no model involved."""

import json
import re
import subprocess
import sys
from collections.abc import Iterator
from datetime import datetime

REPLY_BYTES = 4 << 20
TIMEOUT = 120


def page(brain: str, ref: str = "") -> dict:
    """One `bf read` page; an incomplete or unreadable page stops the review before any output."""
    name = ref or "home"
    try:
        result = subprocess.run(  # noqa: S603 - literal argv; bf is the brain's own offline reader
            ["bf", "read", *([ref] if ref else []), "--brain", brain],  # noqa: S607 - bf from the owner's PATH
            capture_output=True,
            timeout=TIMEOUT,
            check=False,
        )
    except OSError, subprocess.TimeoutExpired:
        raise SystemExit(f"weekly-review: could not read the {name} page") from None
    if result.returncode or len(result.stdout) > REPLY_BYTES:
        raise SystemExit(f"weekly-review: could not read the {name} page")
    try:
        reply = json.loads(result.stdout)
    except ValueError:
        raise SystemExit(f"weekly-review: the {name} page is not JSON") from None
    if not isinstance(reply, dict) or reply.get("problems") or reply.get("stale"):
        # A partial page could hide a project due for review: report nothing rather than too little.
        raise SystemExit(f"weekly-review: the {name} page is incomplete; run bf status")
    return reply


def plain(value: object) -> str:
    """Titles become link labels: one line, without Markdown link delimiters."""
    return re.sub(r"\s+", " ", re.sub(r"[\[\]()<>`]", "", str(value))).strip() or "untitled"


def link(item: dict) -> str:
    return f"[{plain(item.get('title', item['ref']))}]({item['uri']})"


def mention(item: dict) -> str:
    """Name an item without linking it: a link from this dated action would count as newer evidence.

    External text (an invite's title, a mail subject) never enters the action: only its ref does.
    """
    if item.get("external"):
        return f"`{item['ref']}` (external)"
    return f"{plain(item.get('title', item['ref']))} (`{item['ref']}`)"


def render(day: str, home: dict, week: dict) -> Iterator[str]:
    review = [project for project in home.get("projects", []) if project.get("review")]
    yield "---"
    yield "type: action"
    yield "status: active"
    yield f"updated: {day}"
    yield "summary: Weekly review of projects, actions and evidence from the last seven days."
    yield "---"
    yield ""
    yield f"# Weekly review {day}"
    yield ""
    yield "Generated by the weekly-review routine from `bf read` and `bf read 7d`. Update the owning notes,"
    yield "then set `status: done`. This action changes nothing by itself."
    yield ""
    yield "## Projects to review"
    yield ""
    for project in review:
        details = [str(project.get("status", "")), f"updated {str(project.get('time', ''))[:10] or 'never'}"]
        if project.get("new_links"):
            details.append(f"{project['new_links']} newer linked items")
        line = f"- [ ] {link(project)} ({', '.join(details)})"
        yield line + (f". Next: {plain(project['next'])}" if project.get("next") else "")
    if not review:
        yield "Every active project note is current."
    yield ""
    yield "## Last seven days"
    yield ""
    sources = ", ".join(f"{plain(s['source'])} {s['records']}" for s in week.get("sources", []))
    yield f"- {week.get('total', 0)} dated items" + (f"; records by source: {sources}" if sources else "")
    for key, label in (("changed", "Notes changed"), ("actions", "Recent actions")):
        if home.get(key):
            yield f"- {label}: " + ", ".join(mention(item) for item in home[key])
    yield ""
    yield "## Coming week"
    yield ""
    for item in home.get("upcoming", []):
        yield f"- {str(item.get('time', ''))[:16].replace('T', ' ')} UTC: {mention(item)}"
    if not home.get("upcoming"):
        yield "Nothing is scheduled."
    yield ""
    yield "## Resume"
    yield ""
    yield "Work through the unchecked projects; record decisions in their notes with evidence refs."


def main(argv: list[str]) -> int:
    if len(argv) != 3 or not re.fullmatch(r"\d{4}-\d{2}-\d{2}T.*", argv[2]):
        sys.stderr.write("usage: weekly-review.py BRAIN END\n")
        return 2
    brain = argv[1]
    try:
        # The action folder is named after the local date of the run; keep `updated` on the same day.
        day = datetime.fromisoformat(argv[2]).astimezone().date().isoformat()
    except ValueError:
        sys.stderr.write("usage: weekly-review.py BRAIN END\n")
        return 2
    home, week = page(brain), page(brain, "7d")
    if not any(p.get("review") for p in home.get("projects", [])) and not week.get("total"):
        return 0  # Nothing to review: no output, so no action is written.
    sys.stdout.write("\n".join(render(day, home, week)) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
