#!/usr/bin/env python3
"""Weekly review: render the brain's home page and last seven days as a review action; no model involved."""

import json
import re
import subprocess
import sys
from collections.abc import Iterator
from datetime import datetime
from urllib.parse import quote

REPLY_BYTES = 4 << 20
TIMEOUT = 120
MAX_PROJECT_PAGES = 100
TASK_PREVIEW = 10


def page(brain: str, ref: str = "", offset: int = 0) -> dict:
    """One `bf read` page; an incomplete or unreadable page stops the review before any output."""
    name = ref or "home"
    try:
        result = subprocess.run(  # noqa: S603 - literal argv; bf is the brain's own offline reader
            ["bf", "read", *([ref] if ref else []), "--brain", brain, *(["--offset", str(offset)] if offset else [])],  # noqa: S607 - bf from the owner's PATH
            capture_output=True,
            timeout=TIMEOUT,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        raise SystemExit(f"weekly-review: could not read the {name} page") from None
    if result.returncode or len(result.stdout) > REPLY_BYTES:
        raise SystemExit(f"weekly-review: could not read the {name} page")
    try:
        reply = json.loads(result.stdout)
    except ValueError:
        raise SystemExit(f"weekly-review: the {name} page is not JSON") from None
    if not isinstance(reply, dict) or reply.get("problems") or reply.get("stale"):
        # A partial page could hide a project due for review: report nothing rather than too little.
        raise SystemExit(f"weekly-review: the {name} page is incomplete; run bf status")
    return reply


def projects(brain: str) -> list[dict]:
    """The home page is a preview; enumerate projects before claiming none needs review."""
    result = []
    offset = 0
    for _ in range(MAX_PROJECT_PAGES):
        reply = page(brain, "projects", offset)
        result.extend(item for item in reply.get("items", []) if item.get("review"))
        if "next_offset" not in reply:
            return result
        following = reply["next_offset"]
        if type(following) is not int or following <= offset:
            break
        offset = following
    raise SystemExit("weekly-review: the projects listing is incomplete; narrow the selected brain")


def plain(value: object) -> str:
    """Titles become link labels: one line, without Markdown link delimiters."""
    return re.sub(r"\s+", " ", re.sub(r"[\[\]()<>`]", "", str(value))).strip() or "untitled"


def local(value: object) -> str:
    """The local date of a returned time or date: replies state times with their offset, and a date stays its day."""
    try:
        return datetime.fromisoformat(str(value)).astimezone().date().isoformat()
    except ValueError:
        return ""


def when(item: dict) -> str:
    """An item's day or local time as the reply states it: a dated note has no time, a time keeps its offset."""
    if item.get("date"):
        return plain(item["date"])
    try:
        return datetime.fromisoformat(str(item.get("time", ""))).isoformat(sep=" ", timespec="minutes")
    except ValueError:
        return "undated"


def link(item: dict) -> str:
    """A brain-qualified address when several brains answer; otherwise a path from this action's folder."""
    target = item.get("uri") or "../../" + quote(item["ref"], safe="/")
    return f"[{plain(item.get('title', item['ref']))}]({target})"


def code(value: object) -> str:
    """A code span no backtick inside a record id can close, so a ref never becomes Markdown or a link."""
    text = str(value)
    fence = "`" * (max(map(len, re.findall(r"`+", text)), default=0) + 1)
    pad = " " if text.startswith("`") or text.endswith("`") else ""
    return f"{fence}{pad}{text}{pad}{fence}"


def mention(item: dict) -> str:
    """Name an item without linking it: a link from this dated action would count as newer evidence.

    Collected text (an invite's title, a mail subject) never enters the action: only its ref does.
    """
    if item.get("kind") == "record":
        return f"{code(item['ref'])} (record)"
    return f"{plain(item.get('title', item['ref']))} ({code(item['ref'])})"


def render(day: str, home: dict, week: dict) -> Iterator[str]:
    review = [project for project in home.get("projects", []) if project.get("review")]
    yield "---"
    yield "type: action"
    yield "status: draft"
    yield f"updated: {day}"
    yield "summary: Weekly review of projects, actions and evidence from the last seven days."
    yield "---"
    yield ""
    yield f"# Weekly review {day}"
    yield ""
    # One line per paragraph keeps the action stable under Markdown formatters.
    yield (
        "Generated by the weekly-review routine from `bf read`, `bf read tasks` and `bf read 7d`. "
        "Update the owning notes and check off the completed tasks. "
        "Set `status: stable` when this review is ready to rely on. This action changes nothing by itself."
    )
    yield ""
    yield "## Projects to review"
    yield ""
    for project in review:
        details = [str(project.get("status", "")), f"edited {local(project.get('modified')) or 'unknown'}"]
        if project.get("review_due"):
            details.append(f"review due {local(project['review_due'])}")
        if project.get("new_links"):
            details.append(f"{project['new_links']} newer linked items")
        line = f"- [ ] {link(project)} ({', '.join(details)})"
        yield line + (f". Next: {plain(project['next'])}" if project.get("next") else "")
    if not review:
        yield "No project note is due for review."
    yield ""
    yield "## Open tasks"
    yield ""
    tasks = home["tasks"]
    counts = tasks["summary"]
    yield f"{counts['open']} open tasks; {counts['done']} completed across {counts['notes']} notes with checkboxes."
    preview = tasks.get("items", [])[:TASK_PREVIEW]
    for task in preview:
        # Plain bullets and inert refs avoid creating duplicate tasks or new graph evidence.
        yield f"- {plain(task['text'])} ({code(task.get('uri') or task['ref'])}, line {task['line']})."
    if tasks["total"] > len(preview):
        yield f"Showing {len(preview)} of {tasks['total']} open tasks; use `bf read tasks` and follow `next_offset`."
    yield ""
    yield "## Last seven days"
    yield ""
    sources = ", ".join(f"{plain(s['source'])} {s['records']}" for s in week.get("sources", []))
    yield f"- {week.get('total', 0)} dated items" + (f"; records by source: {sources}" if sources else "")
    for key, label in (("changed", "Notes changed"), ("actions", "Recent actions")):
        if home.get(key):
            yield f"- {label}: " + ", ".join(mention(item) for item in home[key])
    yield ""
    yield "## Coming week"
    yield ""
    for item in home.get("upcoming", []):
        yield f"- {when(item)}: {mention(item)}"
    if not home.get("upcoming"):
        yield "Nothing is scheduled."
    yield ""
    yield "## Resume"
    yield ""
    yield "Review the listed projects and open tasks in their owning notes; record decisions there with evidence refs."


def main(argv: list[str]) -> int:
    if len(argv) != 3 or not re.fullmatch(r"\d{4}-\d{2}-\d{2}T.*", argv[2]):
        sys.stderr.write("usage: weekly-review.py BRAIN END\n")
        return 2
    brain = argv[1]
    try:
        # The action folder is named after the local date of the run; keep `updated` on the same day.
        day = datetime.fromisoformat(argv[2]).astimezone().date().isoformat()
    except ValueError:
        sys.stderr.write("usage: weekly-review.py BRAIN END\n")
        return 2
    home, week = page(brain), page(brain, "7d")
    home["projects"] = projects(brain)
    home["tasks"] = page(brain, "tasks")
    if (
        not any(p.get("review") for p in home.get("projects", []))
        and not week.get("total")
        and not home["tasks"]["total"]
    ):
        return 0  # Nothing to review: no output, so no action is written.
    sys.stdout.write("\n".join(render(day, home, week)) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
